name: Docker Image CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgres_version: [9.5, 12, 13]
        asgard_version: [1.2.2]
    steps:
    - uses: actions/checkout@v2
  
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/} for ${{matrix.postgres_version}} and asgard ${{matrix.asgard_version}}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        build-args: |
            POSTGRES_VERSION=${{matrix.postgres_version}}
            ASGARD_VERSION=${{matrix.postgres_version}}
        tags: |
          ghcr.io/jdlom/asgard-postgresql/asgard:pg${{matrix.postgres_version}}-${{matrix.asgard_version}}
