name: Docker Image CI

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: jdlom
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: jdlom/asgard-postgresql/asgard
        tag_with_ref: true
